### ISSUE TITLE
ERROR: Service 'backend' failed to build

### ISSUE THREAD

**Issue by H0UD1NI** [PatrickHallek/automated-irrigation-system#14]
When attempting to, `sudo docker-compose up`
I get:
`Building backend

Step 1/6 : FROM node:10
 ---> 5097189edcdc
Step 2/6 : COPY . /src
 ---> Using cache
 ---> 6553134477ae
Step 3/6 : WORKDIR /src
 ---> Using cache
 ---> 8f4aaa1bbc70
Step 4/6 : RUN npm install
 ---> Running in 34f24dadfe6c
ERROR: Service 'backend' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 139
`

I checked to verify I had npm installed and I do.

Any ideas?

**Comment by H0UD1NI** [comment]
I'm a little confused your statement. I am installing everything through putty/SSH. I am trying to start the project on the pi, I believe is what you are saying? Or, do I need to look at that package.json file on my computer and remove a certain line from it? Everything I have been doing has been through putty/SSH into my pi zero w.

**Comment by H0UD1NI** [comment]
> Hi, thanks for reporting this issue.
> 
> I believe, this could be because of the rpio dependency that you only can install on a raspberry pi. If you are trying to start the project on your computer, you need to remove the rpio dependency line out of the package.json in the backend directory.
> 
> Until now I didn’t find an elegant solution to install dependencies depending on the environment/os.
> Please let me know if that worked.

So, I figured out what you were saying to do. I'm very new to a lot of this, but learning! I removed the "rpio" line from the package.json in the backend directory. I then re-did the docker installation steps (besides "curl -sSL https://get.docker.com | sh" since I believe I don't need to complete that more than once) and I got the same error. I may try reformatting the sd card with a fresh install and remove that rpio line after I download the repository and before docker install.

**Comment by frostie614** [comment]
Hi @H0UD1NI,

I  managed to get it working on my RPI 3 without issue. I dont have the rest of equipment, I only did it to see if I could get the pi parts going :)

Can I ask a few questions?

1. What raspberry pi are you using?
2. What os version are you using? (cat /etc/os-release)
3. What steps you have taken?

``` bash
sudo apt update && sudo apt -y upgrade
sudo apt install git
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi
sudo apt-get install -y libffi-dev libssl-dev
sudo apt-get install -y python3 python3-pip
sudo apt-get remove python-configparser
sudo pip3 install docker-compose
git clone https://github.com/PatrickHallek/automated-irrigation-system
cd automated-irrigation-system
ifconfig # find ip of pi
sudo nano docker-compose.yml # note the .yml, missing from the instructions
sudo docker-compose up
```
If I can help in anyway, let me know.

**Comment by H0UD1NI** [comment]
@frostie614  thanks for all that! 
1. I am using a pi zero w.
2. Using "Raspberry Pi OS (32-bit) with desktop" from [here](https://www.raspberrypi.org/downloads/raspberry-pi-os/)
3. I followed his medium guide located: [Medium](https://medium.com/@patrickhallek1998/automated-smart-home-irrigation-system-9061c391f8e2?sk=3dc152e778acdbd779aed7eae2984f53)

I'll attempt the workflow that you posted and let you know. I'm seeing differences as I created the docker-compose file without a .yml extension... I was always curious about that as I always had to input the ip into a blank document when I would nano into it. I wonder if that's it...

**Comment by H0UD1NI** [comment]
@frostie614 I tried on a clean install and did the exact steps that put in your comment and it gave me the same error as described above.

**Comment by frostie614** [comment]
Ahh okay. I will look into this later.

From [here](https://medium.com/better-programming/understanding-docker-container-exit-codes-5ee79a1d58f6), it looks like the error code indicates a segfault

Can you run: cat /proc/cpuinfo and paste the contents.

I’m thinking it might be related to the MongoDB setup. But I’ll have to look later I’m afriad :)

```
Attention: If you have a Raspberry Pi with a processor other than ARMv7, you need to adjust the image for the mongodb in the docker-compose file. Since this is only suitable for ARMv6.
```

**Comment by H0UD1NI** [comment]
Yeah maybe, it's showing I have an ARMv6. No rush and really appreciate the help! I'll read up on that article you linked.
```
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000005ee12994
Model           : Raspberry Pi Zero W Rev 1.1
```

**Comment by frostie614** [comment]
I managed to reproduce the issue on my pi-zero. Pretty sure it’s the MongoDB instance, but I’m confused as the author said to use a pi zero (armv6). 

Unfortunately, I don’t have a solution yet.

**Comment by H0UD1NI** [comment]
Yeah, that line confused me as well. I can wait and hopefully my plants can too! 😜
  

  
  

  
  
>

**Comment by jakefrancis** [comment]
I had the same issue on my pi zero. 

This might be the reason why.

https://github.com/mKeRix/room-assistant/issues/210#issuecomment-638555442

Here is a potential fix in the same thread. 

https://github.com/mKeRix/room-assistant/issues/210#issuecomment-643684614

I haven't had the opportunity to test it yet. 

Hope this helps.

**Comment by H0UD1NI** [comment]
@jakefrancis , thanks for finding that! I tried just now and input "2.4" into the version and placea "platform: linux/arm/v6" in the frontend section of the docker-compose.yml file and that didn't work. So, I tried to place it in the backend section after "build" and also tried in the mongodb section after the "image" line. Both of those didn't work either. I may be attempting that incorrectly. Let me know if you are able to get it to work. Thanks!

**Comment by frostie614** [comment]
I tried the same with no luck.
I can run it fine using the manual approach.

**Comment by jakefrancis** [comment]
Disregard the proposed fix in my previous post.

I ending up altering both Dockerfiles to point to the pi-zero arm32v6 architecture.

There is no default node:10 image for arm32v6 in the node docker hub.

So I went with node:10-alpine. 

**Frontend**
```
FROM arm32v6/node:10-alpine
COPY . /frontend
WORKDIR /frontend
RUN npm install
RUN npm run build
EXPOSE 4200

```
**Backend**

python, make, and build base needed to be installed as dependencies for rpio due to the slim nature of alpine. 
```
FROM arm32v6/node:10-alpine
COPY . /src
WORKDIR /src
RUN apk add --update-cache python
RUN apk add --update-cache make
RUN apk add --update-cache build-base
RUN npm install
RUN npm rebuild
EXPOSE 3000

```

It appears to have fixed the issue.

I no longer receive.

`ERROR: Service 'backend' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 139`

This is specifically for a Raspberry Pi Zero-W

**Comment by frostie614** [comment]
Thanks @jakefrancis! Works for me!
