### ISSUE TITLE
Get ERROR Message with sudo docker-compose up

### ISSUE THREAD

**Issue by memento21** [PatrickHallek/automated-irrigation-system#25]
Hi,
I get an error message with the command "sudo docker-compose up". The message is the following:

ERROR: Top level object in './docker-compose.yml' needs to be an object not '<class 'str'>'.

Do you have an idea?
Thanks

**Comment by PatrickHallek** [comment]
Have you changed something on the docker-compose.yml file? Sounds like the file is empty

**Comment by memento21** [comment]
Hi,
no it looks so:

version: "3"
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    command: npm start
    volumes:
      - ./:/src
      - /node_modules/
      - /backend/
    depends_on:
      - backend
      - mongodb
    environment:
      - SKIP_PREFLIGHT_CHECK:true
      - PORT:4200
      - HOST=0.0.0.0
      - REACT_APP_BACKEND_URL=http://192.168.178.50:3000

  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/backend
      - /src/backend/node_modules/
    command: npm start
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_DB: "mongodb://mongodb/irrigation"

  mongodb:
    image: ivanmarban/armhf-mongodb
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27018:27017"

**Comment by PatrickHallek** [comment]
Are you sure, you in the correct directory while executing the command?
Otherwise you maybe try to reinstall docker-compose and clone the repository again?

**Comment by memento21** [comment]
In the moment I go via Putty on the raspberry pi. In which directory should it be to start?

**Comment by memento21** [comment]
I was in the wrong directory....:-)
